gaggle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import gaggle.views

urlpatterns = [
                  url(r'^$|^index/$', gaggle.views.index, name='index'),
                  url(r'^privacy/', gaggle.views.privacy, name='privacy'),
                  url(r'^terms/', gaggle.views.terms, name='terms'),
                  url(r'^contact/', gaggle.views.contact, name='contact'),
                  url(r'^about/', gaggle.views.about, name='about'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^competition/', include('competition.urls', namespace='competition')),
                  url(r'^user/', include('user.urls', namespace='user')),
                  url(r'^course/', include('course.urls', namespace='course')),
                  url(r'^forum/', include('pybb.urls', namespace='pybb')),
                  url(r'^i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# CKEditor
urlpatterns += [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# Captcha
urlpatterns += [
    url(r'^ captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView
import pybb.views

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

user/urls.py
from django.conf.urls import url
import user.views

urlpatterns = [
    url(r'^register/$', user.views.register, name='register'),
    url(r'^login/$', user.views.login, name='login'),
    url(r'^logout/$', user.views.logout, name='logout'),
    url(r'^activate/$', user.views.activate, name='activate'),
    url(r'^pending/$', user.views.pending, name='pending'),
    url(r'^confirm/$', user.views.confirm, name='confirm'),
    url(r'^profile/$', user.views.profile, name='profile'),
    url(r'^profile/edit/$', user.views.edit_profile, name='edit_profile'),
    url(r'^profile/(?P<id>\d+)$', user.views.view_user, name='user'),
    url(r'^forget-password/$', user.views.forget_password, name='forget_password'),
    url(r'^reset-password/$', user.views.reset_password, name='reset_password'),
    url(r'^auto-complete/interest$', user.views.auto_complete_interest, name='auto_complete_interest'),
    url(r'^auto-complete/tool$', user.views.auto_complete_tool, name='auto_complete_tool')
]

pybb/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import math

from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models import F, Q
from django.forms.utils import ErrorList
from django.http import HttpResponseRedirect, HttpResponse, Http404, HttpResponseBadRequest,\
    HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic.edit import ModelFormMixin
from django.views.decorators.csrf import csrf_protect
from django.views import generic
from pybb import compat, defaults, util
from pybb.compat import get_atomic_func
from pybb.forms import PostForm, AdminPostForm, AttachmentFormSet, \
    PollAnswerFormSet, PollForm, ForumSubscriptionForm, ModeratorForm
from .models import *
from pybb.permissions import perms
from pybb.templatetags.pybb_tags import pybb_topic_poll_not_voted
from competition.util import active_user_count
from django.template.defaultfilters import slugify


User = compat.get_user_model()
username_field = compat.get_username_field()
Paginator, pure_pagination = compat.get_paginator_class()


class PaginatorMixin(object):
    def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True, **kwargs):
        kwargs = {}
        if pure_pagination:
            kwargs['request'] = self.request
        return Paginator(queryset, per_page, orphans=0, allow_empty_first_page=True, **kwargs)


class RedirectToLoginMixin(object):
    """ mixin which redirects to settings.LOGIN_URL if the view encounters an PermissionDenied exception
        and the user is not authenticated. Views inheriting from this need to implement
        get_login_redirect_url(), which returns the URL to redirect to after login (parameter "next")
    """
    def dispatch(self, request, *args, **kwargs):
        try:
            return super(RedirectToLoginMixin, self).dispatch(request, *args, **kwargs)
        except PermissionDenied:
            if not request.user.is_authenticated():
                from django.contrib.auth.views import redirect_to_login
                return redirect_to_login(self.get_login_redirect_url())
            else:
                return HttpResponseForbidden()

    def get_login_redirect_url(self):
        """ get the url to which we redirect after the user logs in. subclasses should override this """
        return '/'


class IndexView(generic.ListView):
    template_name = 'pybb/index.html'
    context_object_name = 'categories'


    def get_context_data(self, **kwargs):
        ctx = super(IndexView, self).get_context_data(**kwargs)
        categories = ctx['categories']
        for category in categories:
            category.forums_accessed = perms.filter_forums(self.request.user, category.forums.filter(parent=None))
        ctx['categories'] = categories
        ctx['active_users'] = self.request.session.get('active_users', active_user_count())
        return ctx

    def get_queryset(self):
        return perms.filter_categories(self.request.user, Category.objects.all())


class CategoryView(RedirectToLoginMixin, generic.DetailView):

    template_name = 'pybb/index.html'
    context_object_name = 'category'

    def get_login_redirect_url(self):
        # returns super.get_object as there is a conflict with the perms in CategoryView.get_object
        # Would raise a PermissionDenied and never redirect
        return super(CategoryView, self).get_object().get_absolute_url()

    def get_queryset(self):
        return Category.objects.all()

    def get_object(self, queryset=None):
        obj = super(CategoryView, self).get_object(queryset)
        if not perms.may_view_category(self.request.user, obj):
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        ctx = super(CategoryView, self).get_context_data(**kwargs)
        ctx['category'].forums_accessed = perms.filter_forums(self.request.user, ctx['category'].forums.filter(parent=None))
        ctx['categories'] = [ctx['category']]
        ctx['active_users'] = self.request.session.get('active_users', active_user_count())
        return ctx

    def get(self, *args, **kwargs):
        if defaults.PYBB_NICE_URL and (('id' in kwargs) or ('pk' in kwargs)):
            return redirect(super(CategoryView, self).get_object(), permanent=defaults.PYBB_NICE_URL_PERMANENT_REDIRECT)
        return super(CategoryView, self).get(*args, **kwargs)


class ForumView(RedirectToLoginMixin, PaginatorMixin, generic.ListView):

    paginate_by = defaults.PYBB_FORUM_PAGE_SIZE
    context_object_name = 'topic_list'
    template_name = 'pybb/forum.html'

    def dispatch(self, request, *args, **kwargs):
        self.forum = self.get_forum(**kwargs)
        return super(ForumView, self).dispatch(request, *args, **kwargs)

    def get_login_redirect_url(self):
        return self.forum.get_absolute_url()

    def get_context_data(self, **kwargs):
        ctx = super(ForumView, self).get_context_data(**kwargs)
        ctx['forum'] = self.forum
        if self.request.user.is_authenticated():
            try:
                ctx['subscription'] = ForumSubscription.objects.get(
                    user=self.request.user,
                    forum=self.forum
                )
            except ForumSubscription.DoesNotExist:
                ctx['subscription'] = None
        else:
            ctx['subscription'] = None
        ctx['forum'].forums_accessed = perms.filter_forums(self.request.user, self.forum.child_forums.all())
        ctx['active_users'] = self.request.session.get('active_users', active_user_count())
        return ctx

    def get_queryset(self):
        if not perms.may_view_forum(self.request.user, self.forum):
            raise PermissionDenied

        qs = self.forum.topics.order_by('-sticky', '-updated', '-id').select_related()
        qs = perms.filter_topics(self.request.user, qs)
        return qs

    def get_forum(self, **kwargs):
        if 'pk' in kwargs:
            forum = get_object_or_404(Forum.objects.all(), pk=kwargs['pk'])
        elif ('slug' and 'category_slug') in kwargs:
            forum = get_object_or_404(Forum, slug=kwargs['slug'], category__slug=kwargs['category_slug'])
        else:
            raise Http404(_('Forum does not exist'))
        return forum

    def get(self, *args, **kwargs):
        if defaults.PYBB_NICE_URL and 'pk' in kwargs:
            return redirect(self.forum, permanent=defaults.PYBB_NICE_URL_PERMANENT_REDIRECT)
        return super(ForumView, self).get(*args, **kwargs)


class ForumSubscriptionView(RedirectToLoginMixin, generic.FormView):
    template_name = 'pybb/forum_subscription.html'
    form_class = ForumSubscriptionForm

    def get_login_redirect_url(self):
        return reverse('pybb:forum_subscription', args=(self.kwargs['pk'],))

    def get_success_url(self):
        return self.forum.get_absolute_url()

    def get_form_kwargs(self):
        kw = super(ForumSubscriptionView, self).get_form_kwargs()
        self.get_objects()
        kw['instance'] = self.forum_subscription
        kw['user'] = self.request.user
        kw['forum'] = self.forum
        return kw

    def get_context_data(self, **kwargs):
        ctx = super(ForumSubscriptionView, self).get_context_data(**kwargs)
        ctx['forum'] = self.forum
        ctx['forum_subscription'] = self.forum_subscription
        ctx['active_users'] = self.request.session.get('active_users', active_user_count())
        return ctx

    def form_valid(self, form):
        result = form.process()
        if result == 'subscribe-all':
            msg = _((
                'You subscribed to all existant topics on this forum '
                'and you will auto-subscribed to all its new topics.'
            ))
        elif result == 'delete':
            msg = _((
                'You won\'t be notified anymore each time a new topic '
                'is posted on this forum.'
            ))
        elif result == 'delete-all':
            msg = _((
                'You have been subscribed to all current topics in this forum and you won\'t'
                'be auto-subscribed anymore for each new topic posted on this forum.'
            ))
        else:
            msg = _((
                'You will be notified each time a new topic is posted on this forum.'
            ))
        messages.success(self.request, msg, fail_silently=True)
        return super(ForumSubscriptionView, self).form_valid(form)

    def get_objects(self):
        if not self.request.user.is_authenticated():
            raise PermissionDenied
        self.forum = get_object_or_404(Forum.objects.all(), pk=self.kwargs['pk'])
        try:
            self.forum_subscription = ForumSubscription.objects.get(
                user=self.request.user,
                forum=self.forum
            )
        except ForumSubscription.DoesNotExist:
            self.forum_subscription = None

class LatestTopicsView(PaginatorMixin, generic.ListView):

    paginate_by = defaults.PYBB_FORUM_PAGE_SIZE
    context_object_name = 'topic_list'
    template_name = 'pybb/latest_topics.html'

    def get_queryset(self):
        qs = Topic.objects.all().select_related()
        qs = perms.filter_topics(self.request.user, qs)
        return qs.order_by('-updated', '-id')


class PybbFormsMixin(object):

    post_form_class = PostForm
    admin_post_form_class = AdminPostForm
    attachment_formset_class = AttachmentFormSet
    poll_form_class = PollForm
    poll_answer_formset_class = PollAnswerFormSet

    def get_post_form_class(self):
        return self.post_form_class

pybb/templates/pybb/_button_new_topic.html
{% load i18n %}<a href="{% url 'pybb:add_topic' forum.id %}">{% trans "New topic" %}</a>

pybb/templates/pybb/_markitup_preview.html
<html>
<head>
    <style type="text/css">
        blockquote {
          padding: 0 0 0 15px;
          margin: 0 0 20px;
          border-left: 5px solid #eeeeee;
        }
        pre {
            display: block;
            padding: 9.5px;
            margin: 0 0 10px;
            font-size: 13px;
            line-height: 20px;
            word-break: break-all;
            word-wrap: break-word;
            white-space: pre;
            white-space: pre-wrap;
            background-color: whiteSmoke;
            border: 1px solid #CCC;
            border: 1px solid rgba(0, 0, 0, 0.15);
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
{{ html|safe }}
</body>
</html>

pybb/templates/pybb/add_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags staticfiles %}

{% block title %}
{% if forum %}{% trans "New topic" %}{% else %}{% trans "New reply" %}{% endif %}
{% endblock %}

{% block content %}
{% block extra_head %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}
{% block extra_script %}
    {{ block.super }}
    {{ form.media.js }}
    <script type="text/javascript" src="{% static 'pybb/js/jquery.formset.min.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
    {% if forum %}
        {% with object=forum extra_crumb="New topic" %}
            {% include 'pybb/breadcrumb.html' %}
        {% endwith %}
    {% else %}
        {% with object=topic extra_crumb="New reply" %}
            {% include 'pybb/breadcrumb.html' %}
        {% endwith %}
    {% endif %}
{% endblock %}


<h1>{% if forum %}{% trans "New topic" %}{% else %}{% trans "New reply" %}{% endif %}</h1>

{% include "pybb/post_form.html" %}
{% endblock content %}

pybb/templates/pybb/avatar.html
{% load pybb_tags %}
<div class="avatar">
    {% pybb_get_profile user=user as user_profile %}
    <a href="{{ user_profile.get_absolute_url }}">
        {% if user_profile.avatar %}
            {% if 'sorl.thumbnail'|check_app_installed %}
                {% include 'pybb/_sorl_thumbnail_avatar.html' %}
            {% elif 'easy_thumbnails'|check_app_installed %}
                {% include 'pybb/_easy_thumbnail_avatar.html' %}
            {% else %}
                <img src="{{ user_profile.avatar.url }}" alt="{{ user_profile.get_display_name }} avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}"/>
            {% endif %}
        {% else %}
            <img src="{{ PYBB_DEFAULT_AVATAR_URL }}" alt="default avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}"/>
        {% endif %}
    </a>
</div>

pybb/templates/pybb/delete_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags %}

{% block content %}
    <h1>{% trans "Are you sure you want to delete this message?" %}</h1>
    <div class="post-preview well">
        {{ post.body_html|safe }}
    </div>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn btn-danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock content %}

pybb/templates/pybb/edit_privileges.html
{% extends 'pybb/base.html' %}

{% load i18n pybb_tags %}

{% block title %}{% trans "Grant moderator privileges" %}{% endblock title %}

{% block content %}
    <h1>{% trans "Grant moderator privileges" %}</h1>
        <form method="post" action="" class="privileges-edit">
            {% csrf_token %}
            <fieldset>
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    {% for field in form %}
                        {% if field.auto_id %}
                            <label class="control-label {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label }}</label>
                        {% endif %}

                        <div class="multiple-checkbox">
                            {{ field }}

                            {% for error in field.errors %}
                                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                            {% endfor %}

                            {% if field.help_text %}
                                <p class="help-block">
                                    {{ field.help_text|safe }}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </fieldset>
            <p>{% include "pybb/_button_save.html" %}</p>
        </form>
{% endblock content %}

pybb/templates/pybb/form_errors.html
{% if form.non_field_errors %}
    {{ form.non_field_errors }}
{% endif %}
{% if form.non_form_errors %}
    {{ form.non_form_errors }}
{% endif %}

pybb/templates/pybb/form_field.html
{% load pybb_tags %}

<div class="{% if field.is_required %}required{% endif %} {% if field.errors %}error{% endif %}">
    {% if not hide_labels or hide_labels == 0 %}
        <label for="{{ field.auto_id }}">
            {{ field.field.label }}
        </label>
    {% endif %}
    <div class="controls">
        {{ field }}
        {% for error in field.errors %}
            <span class="field-errors">{{ field.errors }}</span>
        {% endfor %}
    </div>
</div>

pybb/templates/pybb/forum_list.html
{% load pybb_tags i18n %}

{% if forum_list %}
    <table class="table table-striped" style="border-bottom: 1px solid #ddd;margin-top:20px;">
        <thead>
            <tr style="background-color: #f9f9f9;border: 1px solid #ccc;">
                <th width='40%'>
                    {% trans "Forum" %}
                </th>
                <th width='12.5%'>
                    {% trans "Topics" %}
                </th>
                <th width='12.5%'>
                    {% trans "Posts" %}
                </th>
                <th>
                    {% trans "Last posts" %}
                </th>
            </tr>
        </thead>
        <tbody>
        {% for forum in forum_list|pybb_forum_unread:user %}
            <tr class="forum-row">
                <td>
                    <div class="state-indicator"></div>
                    <a href="{{ forum.get_absolute_url }}">{{ forum.name }}</a> {% if forum.hidden %}[{% trans "Hidden" %}]{% endif %}
                    <div class="forum-description">
                        {{ forum.description|safe }}
                    </div>
                </td>
                <td>
                    {{ forum.topic_count }}
                </td>
                <td>
                    {{ forum.post_count }}
                </td>
                <td>
                    {% include "pybb/forum_last_update_info.html" %}
                </td>
            </tr>
        {% empty %}
            {% if category %}
                <h3>{% trans "No forums created" %}</h3>
                <a href="{% url 'admin:pybb_forum_add' %}">{% trans "Add forum now" %}</a>
            {%  endif %}
        {% endfor %}
        </tbody>
    </table>
{% endif %}

pybb/templates/pybb/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Forum{% endblock title %}

{% block body %}
<div class="bbs min-wrapper">
    <div style="background-color: #000;">
        <div id="myCarousel" class="wrapper carousel slide">
            <!-- 轮播（Carousel）项目 -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="{% static 'img/re_img/banner_forum.png' %}" alt="First slide" style="width: 100%">
                    <div class="carousel-caption">
                        <h2 style="border: none;">
                            {% trans "Forum" %}
                        </h2>
                        <p>{% trans "Mining all about the biendata" %}</p>
                        <br/>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="" style="background-color: #fff;min-height: 1000px;padding: 20px 0;margin-top:10px;margin-bottom: 40px;">
        <!-- 当前位置 -->
        <div class="wrapper" style="padding: 15px 10px;font-size: 15px;">
            <img src="{% static 'img/re_img/home-1.png' %}" alt="" style="width: 12px;margin: -3px 3px 0 0;">
            <a href="{% url 'index' %}"><span style="color: #4A4A4A">{% trans "Home" %}</span></a>
            <span>&nbsp;&nbsp;>&nbsp;</span>
            <span>{% trans "Forum" %}</span>
        </div>

        <div class="wrapper search">
            <div class="title" id="myScrollspy">
                <ul class="option">
                    <li class="active" role="presentation"><a class="active" href="#home" aria-controls="home" role="tab" data-toggle="tab">{% trans "website" %}</a></li>
                    <li role="presentation"><a href="#home2" aria-controls="home2" role="tab" data-toggle="tab">{% trans "competition" %}</a></li>
                    <li role="presentation" ><a href="#home3" aria-controls="home3" role="tab" data-toggle="tab">{% trans "course" %}</a></li>
                </ul>
                <span>
                    <img src="{% static 'img/re_img/new.png' %}" class="icon">
                    <a href='{% url 'pybb:topic_latest' %}'>{% trans "Last updates in topics" %}</a>
                </span>
            </div>

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    {% for category in categories %}
                        {% if category.name  == "Website"  %}
                            {% include 'pybb/forum_list.html' with forum_list=category.forums_accessed category=category parent_forum='' %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div role="tabpanel" class="tab-pane" id="home2">
                    {% for category in categories %}
                        {% if category.name == "Competition" %}
                            {% include 'pybb/forum_list.html' with forum_list=category.forums_accessed category=category parent_forum='' %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div role="tabpanel" class="tab-pane" id="home3">
                    {% for category in categories %}
                        {% if category.name  == "Course"  %}
                            {% include 'pybb/forum_list.html' with forum_list=category.forums_accessed category=category parent_forum='' %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
</div>
<script>

    var selector = '.option li a';
    $(selector).click(function(){//点击的时候给当前这个加上，其他的移除
        $(selector).removeClass('active');
        $(this).addClass('active');
        
    })

</script>
{% endblock%}

pybb/templates/pybb/latest_topics.html
{% extends 'pybb/base.html' %}

{% load pybb_tags i18n %}

{% block title %}{% trans "Last updates in topics" %}{% endblock title %}

{% block breadcrumb %}
    {% with extra_crumb=_("Last updates in topics") %}
        {% include "pybb/breadcrumb.html" %}
    {% endwith %}
{% endblock %}

{% block content %}
    <div class="forum">
        <h1>{% trans "Last updates in topics" %}</h1>
        {% if forum.headline %}
            <div class="forum-headline alert alert-block">
                {{ forum.headline|safe }}
            </div>
        {% endif %}

        {% include "pybb/pagination.html" %}

        {% include "pybb/topic_list.html" %}

        {% include "pybb/pagination.html" %}
{% comment %}
        {% if user.is_authenticated %}
            <div id='mark-all-as-read'>
                <a href='{% url 'pybb:mark_all_as_read' %}'>
                    {% trans "Mark all topics as read" %}
                </a>
            </div>
        {% endif %}
{% endcomment %}
    </div>
{% endblock content %}