competition/urls.py
from django.conf.urls import include, url
import competition.views

suburls = [
    url(r'^$', competition.views.detail, name='index'),
    url(r'^make-submission/$', competition.views.make_submission, name='make_submission'),
    url(r'^final-submission/$', competition.views.final_submission, name='final_submission'),
    url(r'^my-submission/$', competition.views.my_submission, name='my_submission'),
    url(r'^leaderboard/$', competition.views.leaderboard, name='leaderboard'),
    url(r'^final-leaderboard/$', competition.views.final_leaderboard, name='final_leaderboard'),
    url(r'^winners/$', competition.views.winners, name='winners'),
    url(r'^leaderboard/(?P<submission_pk>\d+)/$', competition.views.leaderboard, name='leaderboard_submission'),
    url(r'^leaderboard-raw/$', competition.views.leaderboard_raw_data, name='leaderboard_raw_data'),
    url(r'^rules/$', competition.views.rules, name='rules'),
    url(r'^rules/accept$', competition.views.accept_rules, name='accept_rules'),
    url(r'^team/submit_as/$', competition.views.submit_as, name='submit_as'),
    url(r'^team/create/(?P<option>\w+)/$', competition.views.create_team, name='create_team'),
    url(r'^team/my_team/$', competition.views.my_team, name='my_team'),
    url(r'^team/alter_name/(?P<name>.+)$', competition.views.ajax_alter_team_name, name='alter_team_name'),
    url(r'^team/invite_user/(?P<email>.+)$', competition.views.ajax_invite_user, name='invite_user'),
    url(r'^team/join_team/$', competition.views.join_team, name='join_team'),
    url(r'^data/$', competition.views.data, name='data'),
    url(r'^data/(?P<name>[-0-9a-zA-Z_.]+)/$', competition.views.data, name='data'),
    url(r'^(?P<slug>[a-zA-Z-_]+)/$', competition.views.detail, name='detail'),
]

urlpatterns = [
    url(r'^$', competition.views.index, name="main"),
    url(r'^(?P<competition_pk>[a-zA-z0-9_]+)/', include(suburls)),
    url(r'^submission/edit/(?P<submission_id>\d+)/$', competition.views.ajax_edit_submission_description,
        name='edit_submission'),
    url(r'^(?P<competition_pk>[a-zA-z0-9_]+)/submission/final/$', competition.views.ajax_final_submit,name='final_submit'),
    url(r'^submission/(?P<submission_pk>\d+)$', competition.views.ajax_query_submission, name='query_submission'),
]

gaggle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import gaggle.views

urlpatterns = [
                  url(r'^$|^index/$', gaggle.views.index, name='index'),
                  url(r'^privacy/', gaggle.views.privacy, name='privacy'),
                  url(r'^terms/', gaggle.views.terms, name='terms'),
                  url(r'^contact/', gaggle.views.contact, name='contact'),
                  url(r'^about/', gaggle.views.about, name='about'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^competition/', include('competition.urls', namespace='competition')),
                  url(r'^user/', include('user.urls', namespace='user')),
                  url(r'^course/', include('course.urls', namespace='course')),
                  url(r'^forum/', include('pybb.urls', namespace='pybb')),
                  url(r'^i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# CKEditor
urlpatterns += [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# Captcha
urlpatterns += [
    url(r'^ captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView
import pybb.views

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

competition/models.py
import os.path
import uuid
import datetime

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.files.storage import FileSystemStorage
from django.core import validators


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


# Storages
data_storage = FileSystemStorage(settings.DATA_ROOT)
submission_storage = FileSystemStorage(settings.SUBMISSION_ROOT)
truth_storage = FileSystemStorage(settings.TRUTH_ROOT)


def resource_file_name(instance, filename):
    return os.path.join(str(uuid.uuid4()) + "_" + filename)


def truth_file_name(instance, filename):
    return os.path.join(instance.name, filename)


class Competition(models.Model):
    CHAMPIONSHIP = 1
    KNOWLEDGE = 2
    category_choice = (
        (CHAMPIONSHIP, "Championship"),
        (KNOWLEDGE, "Knowledge")
    )

    evaluation_choice = (
        ('AUC', 'Area Under ROC Curve'),
        ('RMSE', 'Root of Mean Square Error'),
        ('PRECISION', 'Precision'),
        ('RECALL', 'Recall'),
        ('ACCURACY', 'Accuracy'),
        ('MAP', 'Mean Average Precision'),
        ('NDCG', 'Normalized Discounted Cumulative Gain'),
        ('SMP', 'SMP cup 2016'),
        ('SOHU', 'Sohu Luckydata')
    )

    uid = models.CharField(max_length=50,db_index = True, unique=True, null=True)

    name = models.CharField(max_length=50)
    name_en = models.CharField(max_length=100, null=True)
    description = models.TextField(blank=True)
    description_en = models.TextField(null=True, blank=True)
    host = models.ForeignKey(User, related_name='host_competitions')
    category = models.IntegerField(choices=category_choice)
    award = models.CharField(max_length=10, blank=True)
    sponsor = models.CharField(max_length=100, blank=True)
    sponsor_en = models.CharField(max_length=100, blank=True)

    start_datetime = models.DateTimeField()
    final_submit_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    finalCaculate_datetime = models.DateTimeField(null=True)
    ShowWinner_datetime = models.DateTimeField(null=True)
    valid_end_datetime = models.DateTimeField(null=True)
    winner_start_datetime = models.DateTimeField(null=True)
    winner_end_datetime = models.DateTimeField(null=True)

    max_team_size = models.IntegerField(default=10,
                                        validators=[validators.MinValueValidator(1),
                                                    validators.MaxValueValidator(100)])


    allow_overdue_submission = models.BooleanField()
    invisible = models.BooleanField(default=False)
    submit_per_day = models.IntegerField(default=5)
    final_submit_count = models.IntegerField(default=2)
    final_showwinners_count = models.IntegerField(default=50)
    week_winnernum = models.IntegerField(default=1)
    final_showscore_min = models.FloatField(default=0.5)
    evaluation = models.CharField(max_length=10, choices=evaluation_choice)
    evaluate_reverse = models.BooleanField(default=False)
    num_line = models.IntegerField()
    final_num_line = models.IntegerField(null=True)
    public_ratio = models.IntegerField()
    public_truth = models.FileField(upload_to=truth_file_name, storage=truth_storage)
    private_truth = models.FileField(upload_to=truth_file_name, storage=truth_storage)
    filetype = models.CharField(max_length=10, default='csv')

    introduction = RichTextUploadingField()
    introduction_en = RichTextUploadingField(null=True)
    rules = RichTextUploadingField()
    rules_en = RichTextUploadingField(null=True)
    data_description = RichTextUploadingField()
    data_description_en = RichTextUploadingField(null=True)
    winners = RichTextUploadingField(null=True,blank=True)
    winners_en = RichTextUploadingField(null=True,blank=True)

    logo = models.ImageField(upload_to=resource_file_name, blank=True)
    banner = models.ImageField(upload_to=resource_file_name, blank=True)

    participants = models.ManyToManyField(User, through='Participation', through_fields=('competition', 'user'),
                                          related_name='participate_competitions')

    def last_refresh_time(self):
        now = timezone.now()
        delta = datetime.timedelta(days=(now - self.start_datetime).days)
        return self.start_datetime + delta

    def next_refresh_time(self):
        now = timezone.now()
        delta = datetime.timedelta(days=(now - self.start_datetime).days + 1)
        return self.start_datetime + delta

    def ongoing_days(self):
        return (timezone.now() - self.start_datetime).days + 1

    def is_active(self):
        return timezone.now() < self.end_datetime and timezone.now() >= self.start_datetime

    def is_over(self):
        return timezone.now() > self.end_datetime

    def __str__(self):
        return self.name

    @staticmethod
    def active_competitions():
        now = timezone.now()
        Competition.objects.filter(start_datetime_lte=now, end_datetime_gt=now)

    def has_participant(self, user):
        return self.participants.filter(pk=user.pk).exists()

    def find_team_of_user(self, user):
        try:
            team = Participation.objects.filter(user=user, competition=self).get().team
            return team

        except ObjectDoesNotExist:
            return None


class Team(models.Model):
    members = models.ManyToManyField(User, through='Participation', through_fields=('team', 'user'),
                                     related_name="teams")
    leader = models.ForeignKey(User)
    competition = models.ForeignKey(Competition, related_name="teams")

    name = models.CharField(max_length=20)
    create_datetime = models.DateTimeField()

    final_score = models.FloatField(blank=True)
    final_submission_path = models.FilePathField(blank=True)
    final_submission_name = models.FilePathField(blank=True)

    def submission_count_today(self):
        return self.submissions.filter(submit_datetime__gte=self.competition.last_refresh_time(), status__lte=2, final_submit=False).count()

    def final_submission_count_today(self):
        return self.submissions.filter(submit_datetime__gte=self.competition.last_refresh_time(), status__lte=2, final_submit=True).count()

    def submissions(self):
        return Submission.objects.filter(competition=self.competition,
                                         user__in=self.members.all())

    def submission_left_today(self):
        return self.competition.submit_per_day - self.submission_count_today()

    def submission_count_total(self):
        return self.submissions.filter(status__lte=2).count()

    def size(self):
        return self.members.count()

    def is_single(self):
        return self.members.count() == 1

    def __str__(self):
        return self.name + " : " + self.competition.name


class Timeline(models.Model):
    competition = models.ForeignKey(Competition)
    name = models.CharField(max_length=50)
    mark_datetime = models.DateTimeField()


class Detail(models.Model):
    competition = models.ForeignKey(Competition)
    title = models.CharField(max_length=50)
    content = RichTextUploadingField()
    slug = models.SlugField()
    order = models.IntegerField()
    title_en = models.CharField(max_length=50, null=True)
    content_en = RichTextUploadingField(null=True)

    class Meta:
        unique_together = ('competition', 'slug')

    def __str__(self):
        return self.competition.name + ' - ' + self.title


class Data(models.Model):
    competition = models.ForeignKey(Competition, related_name="data")
    content = models.FileField(upload_to=resource_file_name, storage=data_storage, null=True, blank=True)
    baidu_url = models.URLField(blank=True)
    baidu_code = models.CharField(blank=True, max_length=5)
    dropbox_url = models.URLField(blank=True)

    name = models.CharField(max_length=50)
    size = models.BigIntegerField()

    filetype = models.CharField(max_length=10)

    class Meta:
        unique_together = (
            ('competition', 'name')
        )


class Participation(models.Model):
    competition = models.ForeignKey(Competition)
    user = models.ForeignKey(User)
    team = models.ForeignKey('Team', null=True, blank=True)
    join_datetime = models.DateTimeField()

    def __str__(self):
        return self.user.username + ' : ' + self.competition.name

    class Meta:
        unique_together = (
            ('competition', 'user'),
        )


class Submission(models.Model):
    PENDING = 1
    SUCCESS = 2
    ERROR = 3
    status_choices = (
        (PENDING, 'pending'),
        (SUCCESS, 'success'),
        (ERROR, 'error'),
    )
    content = models.FileField(upload_to=resource_file_name, storage=submission_storage)
    user = models.ForeignKey(User, related_name="submissions")
    competition = models.ForeignKey(Competition, related_name="submissions")
    team = models.ForeignKey(Team, related_name="submissions")

    description = models.CharField(max_length=100)
    display_name = models.CharField(max_length=255)
    submit_datetime = models.DateTimeField()
    message = models.CharField(max_length=50, blank=True)
    final_submit = models.BooleanField(default=False)
    public_score = models.FloatField()
    private_score = models.FloatField()
    remote_addr = models.GenericIPAddressField(blank=True, null=True)

    status = models.IntegerField(choices=status_choices)

    def get_team(self):
        return self.user.teams.get(competition=self.competition)

    def is_editable(self, u):
        return self.user == u or self.get_team().leader == u

    def __str__(self):
        return self.user.username + ", " + self.get_team().name + ', ' + str(self.public_score)

competition/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

competition/templates/competition/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}contact{% endblock %}

{% block body %}
<div class='index min-wrapper'>
    <div class="row">
        <div style="background-color: #fff;">
            <div class="row banner wrapper"
                 {% if competition.banner %}
                 style="background: url({{ MEDIA_URL }}{{ competition.banner }});background-size:cover;"
                 {% endif %}
            >
                <div class="col-md-3 col-sm-3 col-xs-4 competition-logo">
                    {% if competition.logo %}
                        <img src="{{ MEDIA_URL }}{{ competition.logo }}"/ style="height:200px;margin:0px">
                    {% endif %}    
                </div>
                <div class="col-md-9 col-sm-9 col-xs-8 competition-info pt50">
                    {% if lang.code == 'zh-hans' %}
                        <div class="row header">
                            {% if competition.sponsor %}
                                <span>{{ competition.sponsor }}</span> •
                            {% endif %}
                            {% if competition.award %}
                                <span>{{ competition.award }}</span> •
                            {% endif %}
                            {% if competition.uid == 'kddcup2015' %}
                                <span>821 支参赛队伍</span>
                            {% else %}
                                <span>{{ competition.teams.count }} 支参赛队伍</span>
                            {% endif %}
        
                        </div>
                        <div class="row title pt10">
                            {{ competition.name }}
                        </div>
                    {% else %}
                        <div class="row header">
                            {% if competition.sponsor_en %}
                                <span>{{ competition.sponsor_en }}</span> •
                            {% endif %}
                            {% if competition.award %}
                                <span>{{ competition.award }}</span> •
                            {% endif %}
                            {% if competition.uid == 'kddcup2015' %}
                                <span>821 Teams</span>
                            {% else %}
                                <span>{{ competition.teams.count }} Team{{ competition.teams.count|pluralize }}</span>
                            {% endif %}
        
                        </div>
                        <div class="row title pt10">
                            {{ competition.name_en }}
                        </div>
                    {% endif %}   
 
                    <div class="row pt15">
                        <div id="comp-header-stat">
                            <div id="comp-progress">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-info" id="comp-going" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                  
                                    </div>
                                </div>
                            </div>
                            <div id="comp-header-start">
                                {{ competition.start_datetime|date:'Y-m-d' }}
                            </div>
                            <div id="comp-milestone-end">
                                {% if lang.code == 'zh-hans' %}
                                    最终提交
                                {% else %}
                                    Final Submissions
                                {% endif %}
                            </div>
                            <div id="comp-header-end">
                                {{ competition.end_datetime|date:'Y-m-d' }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- 当前位置 -->
        <div class="wrapper" style="padding: 15px 10px;font-size: 15px;">
            <img src="{% static 'img/re_img/home-1.png' %}" alt="" style="width: 12px;margin: -3px 3px 0 0;">
            <a href="{% url 'index' %}"><span style="color: #4A4A4A">{% if lang.code == 'zh-hans' %}主页{% else %}Home{% endif %}</span></a>
            <span>&nbsp;&nbsp;>&nbsp;</span>
            <a href="{% url 'competition:main' %}"><span style="color: #4A4A4A">{% if lang.code == 'zh-hans' %}比赛{% else %}Competitions{% endif %}</span></a>
            <span>&nbsp;&nbsp;>&nbsp;</span>
            <span>{% if lang.code == 'zh-hans' %}{{ competition.name }}{% else %}{{ competition.name_ene }}{% endif %}</span>
        </div>
    
        <div class="wrapper" style="padding: 0 10px;margin-bottom: 40px;">
            <div class="row">
                <div class="col-xs-2 p0" id="myScrollspy" style="width: 17.8%">
                    <ul class="nav nav-tabs nav-stacked" style="width:100%; margin-top:0px">
                        {% if lang.code == 'zh-hans' %}
                            <li><span>介绍</span></li>
                            <li id="intro" class="active"><a href="{% url 'competition:index' competition.uid %}"><span></span>简介</a></li>
                            <li id="rules"><a href="{% url 'competition:rules' competition.uid %}"><span></span>规则</a></li>
                            <li id="data"><a href="{% url 'competition:data' competition.uid %}"><span></span>数据</a></li>
                            {% for detail in competition.detail_set.all %}
                                <li id="{{ detail.slug }}"><a href="{% url 'competition:detail' competition.uid detail.slug %}"><span></span>{{ detail.title }}</a></li>
                            {% endfor %}
    
                            <li><span>提交</span></li>
                            <li id="make-submission"><a href="{% url 'competition:make_submission' competition.uid %}"><span></span>验证提交</a></li>
                            {% if is_final_submit %}
                                <li id="final-submission"><a href="{% url 'competition:final_submission' competition.uid %}"><span></span>最终提交</a></li>
                            {% endif %}
                            <li id="my-submission"><a href="{% url 'competition:my_submission' competition.uid %}"><span></span>我的提交</a></li>
    
                            <li><span>其他</span></li>
                            <li id="my_team"><a href="{% url 'competition:my_team' competition.uid %}"><span></span>我的队伍</a></li>
                            <li id="leaderboard"><a href="{% url 'competition:leaderboard' competition.uid %}"><span></span>排行榜</a></li>
                            {% if is_final %}
                                <li id="final-leaderboard"><a href="{% url 'competition:final_leaderboard' competition.uid %}"><span></span>最终得分</a></li>
                            {% endif %}
                            {% if is_showwinners %}
                                <li id="winners"><a href="{% url 'competition:winners' competition.uid %}"><span></span>获奖名单</a></li>
                            {% endif %}

                            <li><span>&nbsp;</span></li>
                        {% else %}
                            <li><span>Information</span></li>
                            <li id="intro" class="active"><a href="{% url 'competition:index' competition.uid %}"><span></span>Introduction</a></li>
                            <li id="rules"><a href="{% url 'competition:rules' competition.uid %}"><span></span>Rules</a></li>
                            <li id="data"><a href="{% url 'competition:data' competition.uid %}"><span></span>Data</a></li>
                            {% for detail in competition.detail_set.all %}
                                <li id="{{ detail.slug }}"><a href="{% url 'competition:detail' competition.uid detail.slug %}"><span></span>{{ detail.title_en }}</a></li>
                            {% endfor %}
    
                            <li><span>Submission</span></li>
                            <li id="make-submission"><a href="{% url 'competition:make_submission' competition.uid %}"><span></span>Make a submission</a></li>
                            {% if is_final_submit %}
                                <li id="final-submission"><a href="{% url 'competition:final_submission' competition.uid %}"><span></span>Make a final submission</a></li>
                            {% endif %}
                            <li id="my-submission"><a href="{% url 'competition:my_submission' competition.uid %}"><span></span>My submissions</a></li>
    
                            <li><span>Others</span></li>
                            <li id="my_team"><a href="{% url 'competition:my_team' competition.uid %}"><span></span>My Team</a></li>
                            <li id="leaderboard"><a href="{% url 'competition:leaderboard' competition.uid %}"><span></span>Leaderboard</a></li>
                            {% if is_final %}
                                <li id="final-leaderboard"><a href="{% url 'competition:final_leaderboard' competition.uid %}"><span></span>Final Leaderboard</a></li>
                            {% endif %}
                            {% if is_showwinners %}
                                <li id="winners"><a href="{% url 'competition:winners' competition.uid %}"><span></span>Winners list</a></li>
                            {% endif %}

                            <li><span>&nbsp;</span></li>
                        {% endif %}

                    </ul>
                </div>

                <div class="col-xs-10" style="background-color: #fff;padding: 50px;min-height: 800px;width: 74.6%;margin-left:3.8%;margin-bottom:60px;padding-top: 10px;">
                    <!--<div class="col-md-9">-->
                    <div id="myTabContent" class="tab-content">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>    
 
            </div>
        </div>
    
    </div>
</div>
    <script>
        var arr = new Array()
        arr = window.location.href.split('{{ competition.uid }}/');
        var link = arr[1]
        if(link == '') {
            $('#myScrollspy>ul>li').removeClass('active');
            $('#intro').addClass('active');
        } else if (link.indexOf("team") == 0) {
            $('#myScrollspy>ul>li').removeClass('active');
            $('#my_team').addClass('active');
        } else if (link.indexOf("leaderboard") == 0) {
            $('#myScrollspy>ul>li').removeClass('active');
            $('#leaderboard').addClass('active');
        } else {
            $('#myScrollspy>ul>li').removeClass('active');
            $('#'+link.replace('/','')).addClass('active');
        }

        $(function(){
            var final_ratio = 0.9;
            var st = {{ competition.start_datetime|date:'U' }};
            var final = {{ competition.final_submit_datetime|date:'U' }};
            var ed = {{ competition.end_datetime|date:'U' }};
            var now = {% now 'U' %};

            var ratio = 0;
            if(now<st){
                ratio = 0;
            } else if (now<=final){
                ratio = final_ratio * (now-st)/(final-st);
            } else if (now<=ed){
                ratio = final_ratio + (1-final_ratio)*(now-final)/(ed-final)
            } else {
                ratio = 1
            }

            $("#comp-going").css("width", ratio*100 +"%");
        });
    </script>
{% endblock %}

competition/templates/competition/submission_forbidden.html
{% extends "competition/base.html" %}
{% load staticfiles %}

{% block title %} Make Submission {% endblock %}
{% block content %}

    {% if lang.code == 'zh-hans' %}
        <h2 class="mb10">
            当前不允许提交
        </h2>
    {% else %}
        <h2 class="mb10">
            the submission is not allowed now
        </h2>
    {% endif %}


    <div class="competition-detail">
        {{ message }}
    </div>
{% endblock %}

competition/templates/competition/winners.html
{% extends 'competition/base.html'%}

{% block title %} Winners {% endblock %}
{% block content %}

    <div>
        {% if lang.code == 'zh-hans' %}
            {{ competition.winners|safe }}
        {% else %}
            {{ competition.winners_en|safe }}
        {% endif %}
    </div>

{% endblock %}