course/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
import course.views


assignment_urls = [
    url(r'^$', course.views.ViewAssignment.as_view(), name="assignment"),
    url(r'^edit/', course.views.EditAssignment.as_view(), name="edit_assignment"),
    url(r'^detail/$', course.views.EditDetail.as_view(), name="edit_detail"),
    url(r'^detail/new/$', course.views.EditDetailPage.as_view(), name="edit_detail_page"),
    url(r'^detail/edit/(?P<slug>[a-zA-Z-_]+)/$', course.views.EditDetailPage.as_view(), name="edit_detail_page"),
    url(r'^detail/delete/(?P<slug>[a-zA-Z-_]+)/$', course.views.delete_detail_page, name="delete_detail_page"),
    url(r'^data/$', course.views.EditData.as_view(), name='edit_data'),
    url(r'^data/delete/(?P<data_pk>\d+)/$', course.views.delete_data, name='delete_data'),
    url(r'^data/add/$', course.views.add_data, name='add_data'),
    url(r'^evaluation/$', course.views.EditEvaluation.as_view(), name='edit_evaluation'),
]

urlpatterns = [
    url(r'^$', course.views.index, name="index"),
    url(r'^(?P<course_pk>\d+)/$', course.views.ViewCourse.as_view(), name="view"),
    url(r'^(?P<course_pk>\d+)/signup/$', course.views.signup, name="signup"),
    #url(r'^(?P<course_pk>\d+)/applycourse/$', course.views.applycourse, name="applycourse"),
    url(r'^(?P<course_pk>\d+)/students/(?P<page>[0-9]+)/$', course.views.ViewStudents.as_view(), name="students"),
    url(r'^(?P<course_pk>\d+)/leaderboard/$', course.views.ViewLeaderboard.as_view(), name='leaderboard'),
    url(r'^(?P<course_pk>\d+)/disapprove/(?P<student_pk>[0-9]+)/$', course.views.disapprove, name="disapprove"),
    url(r'^(?P<course_pk>\d+)/edit/$', course.views.EditCourse.as_view(), name="edit"),
    url(r'^(?P<course_pk>\d+)/delete_ta/(?P<ta_pk>\d+)/$', course.views.delete_ta, name="delete_ta"),
    url(r'^(?P<course_pk>\d+)/add_ta/$', course.views.add_ta, name="add_ta"),
    url(r'^(?P<course_pk>\d+)/add_stu/$', course.views.add_stu, name="add_stu"),
    url(r'^(?P<course_pk>\d+)/new_assignment/$', course.views.CreateAssignment.as_view(), name="create_assignment"),
    url(r'^(?P<course_pk>\d+)/(?P<assignment_pk>\d+)/', include(assignment_urls)),
    url(r'^(?P<course_pk>\d+)/(?P<assignment_pk>\d+)/detail/$', course.views.EditDetail.as_view(), name="edit_detail")
]

gaggle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import gaggle.views

urlpatterns = [
                  url(r'^$|^index/$', gaggle.views.index, name='index'),
                  url(r'^privacy/', gaggle.views.privacy, name='privacy'),
                  url(r'^terms/', gaggle.views.terms, name='terms'),
                  url(r'^contact/', gaggle.views.contact, name='contact'),
                  url(r'^about/', gaggle.views.about, name='about'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^competition/', include('competition.urls', namespace='competition')),
                  url(r'^user/', include('user.urls', namespace='user')),
                  url(r'^course/', include('course.urls', namespace='course')),
                  url(r'^forum/', include('pybb.urls', namespace='pybb')),
                  url(r'^i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# CKEditor
urlpatterns += [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# Captcha
urlpatterns += [
    url(r'^ captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView
import pybb.views

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

course/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django import http
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse, reverse_lazy
import django.views.generic.edit
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib import messages

from course.models import *
from course.forms import *
import competition.models
import os
import datetime
from django.utils.translation import ugettext as _
from competition.util import active_user_count
from .util import course_leaderboard_data,stu_leaderboard_data


def is_member_of(group_name):
    def test(user):
        return user.groups.filter(name=group_name).exists()

    return test


is_tutor = is_member_of("tutors")
# Views

def index(request):
    active_users = request.session.get('active_users', active_user_count())

    over_courses = Course.objects.filter(end_datetime__lt = timezone.now()).order_by("-start_datetime")
    go_courses = Course.objects.filter(start_datetime__gt = timezone.now()).order_by("-start_datetime")
    in_courses = Course.objects.filter(start_datetime__lte = timezone.now(), end_datetime__gte = timezone.now()).order_by("-start_datetime")

    render_context = {
        "over_courses": over_courses,
        "go_courses": go_courses,
        "in_courses": in_courses,
        "over_num": over_courses.count(),
        "go_num": go_courses.count(),
        "in_num": in_courses.count(),
        "active_users": active_users,
    }

    if(request.user.is_authenticated()):
        render_context["tutor_courses"] = request.user.tutor_courses.all().order_by("-start_datetime")
        render_context["assistant_courses"] = request.user.ta_courses.all().order_by("-start_datetime")
        render_context["attend_courses"] = request.user.attend_courses.all().order_by("-start_datetime")
        render_context["tutor_num"] = render_context["tutor_courses"].count()
        render_context["assistant_num"] = render_context["assistant_courses"].count()
        render_context["attend_num"] = render_context["assistant_courses"].count()

    return render(request, "course/index.html", render_context)


class CourseMixin:
    def __init__(self):
        self.course = None
        self.user = None

    def get_context_data(self, **kwargs):
        context = super(CourseMixin, self).get_context_data(**kwargs)
        if is_tutor(self.user):
            context['all_courses'] = self.user.tutor_courses.all()
        else:
            context['all_courses'] = [self.course]

        context['course'] = self.course
        context['manage'] = (self.user == self.course.tutor) or \
                            (self.course.teaching_assistants.filter(pk=self.user.pk).exists())

        context['signed_up'] = self.course.students.filter(pk=self.user.pk).exists()
        context['form_helper'] = form_helper
       
        return context


class AssignmentMixin(CourseMixin):
    def __init__(self):
        self.assignment = None
        self.competition = None

    def get_context_data(self, **kwargs):
        context = super(AssignmentMixin, self).get_context_data(**kwargs)
        context['assignment'] = self.assignment
        context['competition'] = self.competition
        return context



class ViewCourse(CourseMixin, generic.TemplateView):
    template_name = "course/course.html"

    def __init__(self):
        super(ViewCourse, self).__init__()

    def dispatch(self, request, course_pk, *args, **kwargs):
        self.user = request.user
        self.course = get_object_or_404(Course, pk=course_pk)
        if not self.course.open_navigate:
            messages.info(request,_("this course can't Register now"))
        return super(ViewCourse, self).dispatch(request, course_pk, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewCourse, self).get_context_data(**kwargs)
        if is_tutor(self.user):
            context['all_courses'] = self.user.tutor_courses.all()
        else:
            context['all_courses'] = [self.course]

        context['course'] = self.course
        context['manage'] = (self.user == self.course.tutor)
        context['assistant'] = (self.course.teaching_assistants.filter(pk=self.user.pk).exists())
        context['active_users'] = self.request.session.get('active_users', active_user_count())

        if context['signed_up']:
            context['stu_rank'] = stu_leaderboard_data(self.course.competition, self.course, self.user)
        #context['team']
        return context


class EditCourse(CourseMixin, generic.UpdateView):
    template_name = "course/edit_course.html"

    model = Course
    fields = ['name', 'school', 'start_datetime', 'end_datetime', 'description', 'register_code', 'open_navigate',
              'open_signup',
              ]

    def dispatch(self, request, course_pk, *args, **kwargs):
        self.user = request.user
        self.course = get_object_or_404(Course, pk=course_pk)
        if self.course.tutor != self.user:
            return http.HttpResponseForbidden()
        return super(EditCourse, self).dispatch(request, course_pk, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.course

    def get_context_data(self, **kwargs):
        context = super(EditCourse, self).get_context_data(**kwargs)
        context['active_users'] = self.request.session.get('active_users', active_user_count())
        return context

    def get_success_url(self):
        return reverse('course:view', args=(self.course.pk,))


@login_required
def delete_ta(request, course_pk, ta_pk):
    course = get_object_or_404(Course, pk=course_pk)
    ta = get_object_or_404(User, pk=ta_pk)
    if course.tutor != request.user:
        return http.HttpResponseForbidden()

    course.teaching_assistants.remove(ta)
    return http.HttpResponseRedirect(reverse('course:view', args=(course.pk,)))


@require_POST
@login_required
def add_ta(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    if course.tutor != request.user:
        return http.HttpResponseForbidden()
    ta_email = request.POST.get('email', None)
    #messages.success(request, ta_email)
    try:
        ta = User.objects.get(email=ta_email)
        #messages.error(request, ta.username)
        course.teaching_assistants.add(ta)
    except User.DoesNotExist:
        messages.error(request, _("Email ") + ta_email + _(" not found"))
    return http.HttpResponseRedirect(reverse('course:view', args=(course.pk,)))

@require_POST
@login_required
def add_stu(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    if course.tutor != request.user:
        return http.HttpResponseForbidden()
    stu_email = request.POST.get('email', None)
    
    try:
        stu = User.objects.get(email=stu_email)
        course.students.add(stu)
        messages.success(request, _("You has successfully added student ") + stu.username)
    except User.DoesNotExist:
        messages.error(request, _("Email ") + stu_email + _(" not found"))
    return http.HttpResponseRedirect(reverse('course:view', args=(course.pk,)))


class CreateAssignment(CourseMixin, generic.FormView):
    template_name = "course/edit_assignment.html"
    form_class = CreateProjectForm

    initial = {}

    def __init__(self):
        super(CreateAssignment, self).__init__()
        self.competition = None
        self.assignment = None

    def dispatch(self, request, course_pk, *args, **kwargs):
        self.user = request.user
        self.course = get_object_or_404(Course, pk=course_pk)
        if self.user != self.course.tutor:
            return http.HttpResponseForbidden()
        return super(CreateAssignment, self).dispatch(request, course_pk, *args, **kwargs)

    def form_valid(self, form):
        comp = form.save(commit=False)
        comp.host = self.user
        comp.category = competition.models.Competition.KNOWLEDGE
        comp.award = "Credit"
        comp.allow_overdue_submission = False
        comp.evaluation = "AUC"
        comp.num_line = 0
        comp.public_ratio = 0
        comp.public_truth = ""
        comp.private_truth = ""
        comp.save()
        self.competition = comp

        assignment = Assignment(
            title=comp.name,
            description=comp.description,
            course=self.course,
            open=True,
            create_datetime=timezone.now(),
            start_datetime=comp.start_datetime,
            end_datetime=comp.end_datetime,
            competition=comp
        )
        assignment.save()
        self.assignment = assignment
        return super(CreateAssignment, self).form_valid(form)

    def get_success_url(self):
        return reverse("course:edit_data", args=(self.course.pk, self.assignment.pk,))


class ViewAssignment(AssignmentMixin, generic.TemplateView):
    template_name = "course/assignment.html"

    def dispatch(self, request, course_pk, assignment_pk, **kwargs):
        self.course = get_object_or_404(Course, pk=course_pk)
        self.user = request.user
        self.assignment = get_object_or_404(Assignment, pk=assignment_pk)
        self.competition = self.assignment.competition
        return super(ViewAssignment, self).dispatch(request, course_pk, assignment_pk, **kwargs)


class EditAssignment(AssignmentMixin, generic.UpdateView):
    template_name = "course/edit_assignment.html"
    # model = competition.models.Competition
    # fields = ['name', 'description', 'max_team_size', 'start_datetime', 'end_datetime', 'logo']
    # labels = {
    #     'max_team_size': 'Maximum team size',
    #     'name': 'Assignment title',
    #     'logo': 'Logo (optional)'
    # }
    form_class = CreateProjectForm

course/templates/course/components/course_detail.html
{% load staticfiles %}

{% if lang.code == 'zh-hans' %}
    <li class="">
        <div class="start"></div>
        <div class="content">
            {% if course.logo %}
                <a href="{% url 'course:view' course.pk %}">
                <img src="{{ MEDIA_URL }}{{ course.logo }}" style="width:150px;height:129px;padding-left: 51px;padding-top: 19px;padding-bottom: 19px;">
                </a>
            {% endif %}
    
            <div class="thumbnail_wrap1">
                <h4>
                    <a href="{% url 'course:view' course.pk %}" style="color:#000;">
                        <span class="des_text p0" title="{{ course.name }}">{{ course.name }}</span>
                    </a>
                </h4>
                <p style="color: #9B9B9B;padding-top: 3px;" title="{{ course.description }}" class="des_twoline">{{ course.description }}</p>
                <div class="row">
                    <dl class="col-xs-6 p0">
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/skls.png' %}">
                            <span>授课老师: {{ course.tutor_name }}</span>
                        </dd>
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/zbf.png' %}">
                            <span>所属学院: {{ course.school }}</span>
                        </dd>
                    </dl>
                    <dl class="col-xs-6 p0">
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/skrq.png' %}">
                            <span>上课日期: {{ course.start_datetime|date:'Y-m-d' }} ~ {{ course.end_datetime|date:'Y-m-d' }}</span>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </li>
{% else %}
    <li class="">
        <div class="start"></div>
        <div class="content">
            {% if course.logo %}
                <a href="{% url 'course:view' course.pk %}">
                <img src="{{ MEDIA_URL }}{{ course.logo }}" style="width:150px;height:129px;padding-left: 51px;padding-top: 19px;padding-bottom: 19px;">
                </a>
            {% endif %}
    
            <div class="thumbnail_wrap1">
                <h4>
                    <a href="{% url 'course:view' course.pk %}" style="color:#000;">
                        <span class="des_text p0" title="{{ course.name_en }}">{{ course.name_en }}</span>
                    </a>
                </h4>
                <p style="color: #9B9B9B;padding-top: 3px;" title="{{ course.description_en }}" class="des_twoline">{{ course.description_en }}</p>
                <div class="row">
                    <dl class="col-xs-6 p0">
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/skls.png' %}">
                            <span>Teacher: {{ course.tutor_name }}</span>
                        </dd>
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/zbf.png' %}">
                            <span>School: {{ course.school_en }}</span>
                        </dd>
                    </dl>
                    <dl class="col-xs-6 p0">
                        <dd style="color: #000;">
                            <img class="icon2" src="{% static 'img/re_img/skrq.png' %}">
                            <span>Timeline: {{ course.start_datetime|date:'Y-m-d' }} ~ {{ course.end_datetime|date:'Y-m-d' }}</span>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </li>
{% endif %}

course/templates/course/components/course_info.html
<div class="col-sm-6 col-md-6 col-xs-6 mb15">
    <div class="thumbnail row">
        <div class="col-sm-4 col-md-4 mt10 mb10">
            {% if course.logo %}
            <a href="{% url 'course:view' course.pk %}">
            <img src="{{ MEDIA_URL }}{{ course.logo }}" style="width:120px; height:120px">
            </a>
            {% endif %}
        </div>
        <div class="caption col-sm-8 col-md-8">
        {% if lang.code == 'zh-hans' %}
            <h6 class="row">
                <a class="col-xs-11 des_text p0" href="{% url 'course:view' course.pk %}">{{ course.name }}</a>
            </h6>
            <small title="{{ course.description }}" class="des_twoline">{{ course.description }}</small>
            <div class="mt5">
                <dl>
                    <dt>授课老师:</dt>
                    <dd>{{ course.tutor_name }}</dd>
                    <dt>所属院校:</dt>
                    <dd>{{ course.school }}</dd>
                    <dt>开始时间:</dt>
                    <dd>{{ course.start_datetime }}</dd>
                    <dt>结束时间:</dt>
                    <dd>{{ course.end_datetime }}</dd>
                </dl>
            </div>
        {% else %}
            <h6 class="row">
                <a class="col-xs-11 des_text p0" href="{% url 'course:view' course.pk %}">{{ course.name_en }}</a>
            </h6>
            <small title="{{ course.description }}" class="des_twoline">{{ course.description_en }}</small>
            <div class="mt5">
                <dl>
                    <dt>Tutor:</dt>
                    <dd>{{ course.tutor_name }}</dd>
                    <dt>School:</dt>
                    <dd>{{ course.school_en }}</dd>
                    <dt>Start:</dt>
                    <dd>{{ course.start_datetime }}</dd>
                    <dt>End:</dt>
                    <dd>{{ course.end_datetime }}</dd>
                </dl>
            </div>
        {% endif %}
        </div>
    </div>
</div>

course/templates/course/components/course_sidebar.html
<div class="col-xs-6 col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" style="z-index: 1;">
    {% if new_course %}
    <div class="panel panel-default">
        <div class="panel-heading">New Course</div>
    </div>
    {% endif %}
    {% for course in courses %}
    <div class="panel panel-default">
            <div class="panel-heading"><a href="{% url 'course:view' course.pk %}"> {{ course.name }} </a></div>
            <ul class="list-group">
                {% for assignment in course.assignments.all %}
                    <li class="list-group-item">
                        <a href="{% url 'course:assignment' course.pk assignment.pk %}">{{ assignment.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>
</div>
<div class="col-xs-12 col-sm-9 col-md-9">
    <p class=" visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
    </p>
</div>

course/templates/course/components/create_pipeline.html
{% load select_active %}
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <ul class="bread-nav">
            <li class="{% select_active 'basic' active %}">
                <a href="{% url 'course:edit_assignment' course.pk assignment.pk %}">
                    Basic Information<span class="glyphicon glyphicon-menu-right"></span>
                </a>
            </li>
{#            <li class="{% select_active 'privacy' active %}">#}
{#                <a href="{% url 'course:edit_detail' course.pk assignment.pk %}">#}
{#                    Privacy Settings<span class="glyphicon glyphicon-menu-right"></span>#}
{#                </a>#}
{#            </li>#}
            <li class="{% select_active 'data' active %}">
                <a href="{% url 'course:edit_data' course.pk assignment.pk %}">
                    Data Files<span class="glyphicon glyphicon-menu-right"></span>
                </a>
            </li>
            <li class="{% select_active 'detail' active %}">
                <a href="{% url 'course:edit_detail' course.pk assignment.pk %}">
                    Detail Pages<span class="glyphicon glyphicon-menu-right"></span>
                </a>
            </li>
            <li class="{% select_active 'evaluation' active %}">
                <a href="{% url 'course:edit_evaluation' course.pk assignment.pk %}">Evaluation</a>
            </li>
        </ul>
    </div>
</div>