gaggle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import gaggle.views

urlpatterns = [
                  url(r'^$|^index/$', gaggle.views.index, name='index'),
                  url(r'^privacy/', gaggle.views.privacy, name='privacy'),
                  url(r'^terms/', gaggle.views.terms, name='terms'),
                  url(r'^contact/', gaggle.views.contact, name='contact'),
                  url(r'^about/', gaggle.views.about, name='about'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^competition/', include('competition.urls', namespace='competition')),
                  url(r'^user/', include('user.urls', namespace='user')),
                  url(r'^course/', include('course.urls', namespace='course')),
                  url(r'^forum/', include('pybb.urls', namespace='pybb')),
                  url(r'^i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# CKEditor
urlpatterns += [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# Captcha
urlpatterns += [
    url(r'^ captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView
import pybb.views

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

user/urls.py
from django.conf.urls import url
import user.views

urlpatterns = [
    url(r'^register/$', user.views.register, name='register'),
    url(r'^login/$', user.views.login, name='login'),
    url(r'^logout/$', user.views.logout, name='logout'),
    url(r'^activate/$', user.views.activate, name='activate'),
    url(r'^pending/$', user.views.pending, name='pending'),
    url(r'^confirm/$', user.views.confirm, name='confirm'),
    url(r'^profile/$', user.views.profile, name='profile'),
    url(r'^profile/edit/$', user.views.edit_profile, name='edit_profile'),
    url(r'^profile/(?P<id>\d+)$', user.views.view_user, name='user'),
    url(r'^forget-password/$', user.views.forget_password, name='forget_password'),
    url(r'^reset-password/$', user.views.reset_password, name='reset_password'),
    url(r'^auto-complete/interest$', user.views.auto_complete_interest, name='auto_complete_interest'),
    url(r'^auto-complete/tool$', user.views.auto_complete_tool, name='auto_complete_tool')
]

user/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from .models import UserInfo
from captcha.fields import CaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Fieldset, Field, MultiField, MultiWidgetField
from crispy_forms.bootstrap import FormActions
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, validators=[
        RegexValidator(r'^[a-zA-Z][a-zA-Z0-9_]+$',
                       message="Username can contain only numbers, letters and underscores")],
                       required=True)
    display_name = forms.CharField(max_length=30, label="Display Name",
                                   validators=[RegexValidator(r"^(\w|\d|[ ,_'])+$")], required=True)
    real_name = forms.CharField(max_length=50, label="Real Name",
                                   validators=[RegexValidator(r"^(\w|\d|[ ,_'])+$")], required=True)

    organization = forms.CharField(max_length=500, label="Organization",
                                   validators=[RegexValidator(r"^(\w|\d|[ ,_'])+$")], required=True)

    email = forms.EmailField(required=True)

    password = forms.CharField(widget=forms.PasswordInput, max_length=20, min_length=7, required=True)
    password_confirm = forms.CharField(label="Confirm Password",
                                       widget=forms.PasswordInput, max_length=20, min_length=7, required=True)

    captcha = CaptchaField(label="Validation Code")

    receive_update = forms.BooleanField(initial=True, label="Receive updates", required=False,
                                        widget=forms.CheckboxInput())

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_action = reverse('user:register')
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-4"
        self.helper.field_class = "col-md-7"
        # self.helper.
        self.helper.layout = Layout(
            Field('username', placeholder="The user name you hope to login"),
            Field('display_name', placeholder="Your real name displayed to others"),
            Field('real_name', placeholder="For authentication, won't displayed"),
            Field('organization', placeholder="For authentication"),
            Field('email', placeholder="We'll send an validation email later"),
            Field('password', placeholder="At least 7 characters"),
            Field('password_confirm', placeholder="Type the password again"),
            Field('captcha', placeholder="Captcha"),
            Field('receive_update'),
            FormActions(Submit('submit', _('Sign Up')))
        )

    def clean(self):
        errors = []
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')

        if password_1 and password_2 != password_1:
            errors.append(forms.ValidationError(_("Password doesn't match!")))

        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if username and User.objects.filter(username=username).exists():
            errors.append(forms.ValidationError(_("Username has been used!")))
        if email and User.objects.filter(email=email).exists():
            errors.append(forms.ValidationError(_("Email address has been used!")))

        if len(errors) > 0:
            raise forms.ValidationError(errors)

        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(max_length=20, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    remember = forms.BooleanField(label="Remember Me", initial=True, required=False, widget=forms.CheckboxInput())
    next = forms.CharField(max_length=200, widget=forms.HiddenInput, required=False, initial='')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.add_input(Submit('submit', _('Login')))


class ProfileEditForm(forms.ModelForm):
    interests = forms.CharField(widget=forms.HiddenInput, required=True)
    tools = forms.CharField(widget=forms.HiddenInput, required=True)

    interests_edit = forms.CharField(widget=forms.Textarea(attrs={'rows': 1}), required=False)
    tools_edit = forms.CharField(widget=forms.Textarea(attrs={'rows': 1}), required=False)

    class Meta:
        model = UserInfo
        fields = ['organization', 'bio', 'personal_tag', 'city', 'province', 'country',
                  'github_account', 'linkedin_url', 'twitter_account']

    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_id = 'id-profile-edit-form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('user:edit_profile')
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Fieldset(
                _('Organization'),
                Field('organization', placeholder=_("Name of your school department, company, or something else")),
            ),
            Fieldset(
                _('Bio'),
                Field('personal_tag', placeholder=_("Enter personal tagline here")),
                Field('bio', placeholder=_("Bio here")),
            ),
            Fieldset(
                _('Location'),
                Field('city', placeholder=_("City of residence")),
                Field('province', placeholder=_("State/Province")),
                Field('country', Placeholder=_("Country of residence"))
            ),
            Fieldset(
                _('Social'),
                Field('github_account', placeholder=_("Your github account")),
                Field('linkedin_url', placeholder=_("Your linkedin profile url")),
                Field('twitter_account', placeholder=_("Your twitter account"))
            ),
            Fieldset(
                _('Skills(Required)'),
                Field('interests_edit',
                      placeholder=_("Machine learning techniques you are familiar with. Split with ','")),
                Field('tools_edit', placeholder=_("Tools you are familiar with. Split with ','")),
                Field('tools'),
                Field('interests'),
            ),
            FormActions(Submit('submit', _('Save changes')))
        )


class ActivateForm(forms.Form):
    key = forms.CharField(max_length=128, widget=forms.HiddenInput)
    captcha = CaptchaField(label="Validation Code")

    def __init__(self, *args, **kwargs):
        super(ActivateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-activate-form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('user:activate')
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-7"

        self.helper.layout = Layout(
            Field('captcha'),
            Field('key'),
            FormActions(Submit('submit', _('Activate')))
        )


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(label="Email")
    captcha = CaptchaField(label="Validation Code")

    def __init__(self, *args, **kwargs):
        super(ForgetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-forgot-password-form'
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-7"
        self.helper.form_method = 'post'

        self.helper.form_action = reverse('user:forget_password')

        self.helper.layout = Layout(
            Field('email', placeholder=_("The email address used in registration")),
            Field('captcha'),
            FormActions(
                Submit('submit', _('Reset Password'))
            )
        )


class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, max_length=20, )
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password", max_length=20)
    key = forms.CharField(widget=forms.HiddenInput, max_length=128)
    captcha = CaptchaField(label="Validation Code")

    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-4"
        self.helper.field_class = "col-md-7"
        self.helper.form_id = 'id-reset-password-form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('user:reset_password')

        self.helper.layout = Layout(
            Field("password", placeholder=_("New password")),
            Field("password_confirm", placeholder=_("Type new password again")),
            Field("key"),
            Field('captcha'),
            FormActions(
                Submit('submit', _('Reset'))
            )
        )

    def clean(self):
        errors = []
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')

        if password_1 and password_2 != password_1:
            errors.append(forms.ValidationError(_("Password doesn't match!")))
        if len(errors) > 0:
            raise forms.ValidationError(errors)

user/templates/user/activate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% get_language_info for LANGUAGE_CODE as lang %}
{% block title %}Activate your account {% endblock %}
{% block body %}
    <div class="row pt30">
        <div class="col-md-6 col-md-offset-3  col-xs-6 col-xs-offset-3  col-sm-6 col-sm-offset-3">
           
            {% if lang.code == 'zh-hans' %}
                <h1 class="mb10">
                    激活你的账户
                </h1>
            {% else %}
                <h1 class="mb10">
                    Activate Your Account
                </h1>
            {% endif %}

            {% crispy form %}
        </div>
    </div>

{% endblock %}

user/templates/user/confirm.html
{% extends 'base.html' %}
{% block title %}Activate your account {% endblock %}
{% block body %}
    {#    A validation mail has been sent to {{ user.email }}. Click#}
    {#    <a href="{% url 'user:resend_activation_mail' activation.id %}">here</a> to send a new one.#}
    <div class="row pt30">
        <div class="col-md-6 col-md-offset-3  col-xs-6 col-xs-offset-3  col-sm-6 col-sm-offset-3">
            {% if lang.code == 'zh-hans' %}
                <h1 class="mb10">
                    感谢你的注册
                </h1>
                <p>
                    我们已经发了一封邮件给你.请点击里面的链接激活你的账户.
                    该邮件可能被某些服务器分类为垃圾邮件.
                </p>
            {% else %}
                <h1 class="mb10">
                    Thanks for registering
                </h1>
                <p>
                    We have sent an email to you. Please click the link inside to activate your account.
                    It may be classified as spam by some email service providers.
                </p>
            {% endif %}
            
        </div>
    </div>
{% endblock %}

user/templates/user/edit_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load gravatar %}
{% block title %}Profile{% endblock %}


{% block body %}
<style>
    .controls>input,.controls>textarea,.controls>select{
        width: 60% !important;
    }

</style>

<div class="mt25 ml10 mr10 pb50">
    <div class="row mb20">
        <div class="userinfo-header col-md-6 col-xs-6 col-sm-6 lh35" style="padding-left: 0px;">
            <span class="display_name">{{ user.info.display_name }} </span>
            <span class="personal_tag">{{ user.info.personal_tag }}</span>
        </div>
    </div>

    <div class="pt25 pb10 pl30 pr30 mb20" style="background-color: #F7F7F7;">
        <div class="row">
            <div class="col-sm-3 col-md-3 col-xs-3 mb10">
                    <div class="img-shade">
                        <img src="{% static 'img/default.jpg' %}" width="100%" style="width: 150px;"/>
                        <div class="shade">
                            <div class="left-top"></div>
                            <div class="left-bottom"></div>
                            <div class="right-top"></div>
                            <div class="right-bottom"></div>
                        </div>
                    </div>
            </div>
            <div class="col-sm-9 col-md-9 col-xs-9">
                <p><img src="{% static 'img/tag2.png' %}" width="100%" style="width: 15px;padding-right: 5px;"/>{{ user.email }}</p>
        
                {% if lang.code == 'zh-hans' %}            
                    <p><img src="{% static 'img/tag1.png' %}" width="100%" style="width: 15px;padding-right: 5px;"/>加入时间为 {{ user.date_joined|date:'b d Y' }}</p>
                {% else %}
                    <p><img src="{% static 'img/tag1.png' %}" width="100%" style="width: 15px;padding-right: 5px;"/>Joined at {{ user.date_joined|date:'b d Y' }}</p>
                {% endif %}

            </div>
        </div>

        <div class="poa t10 r10">
            {% if user.info.linkedin_url %}
            <a href="https://www.linkedin.com/in/{{ user.info.linkedin_url }}" class="" style="display: inline-block;width: 34px;height: 40px;background-image: url('/static/img/list.png');background-repeat: no-repeat;background-position: -10px 0px;background-size: 200px;margin: 0 5px;"></a>
            {% endif %}
            {% if user.info.github_account %}
            <a href="https://github.com/{{ user.info.github_account }}" class="" style="display: inline-block;width: 34px;height: 40px;background-image: url('/static/img/list.png');background-repeat: no-repeat;background-position: -108px 0px;background-size: 200px;margin: 0 5px;"></a>
            {% endif %}
            {% if user.info.twitter_account %}
            <a href="#" class="" style="display: inline-block;width: 34px;height: 40px;background-image: url('/static/img/list.png');background-repeat: no-repeat;background-position: -58px 0px;background-size: 200px;margin: 0 5px;"></a>
            {% endif %}
                        <a href="#" class="" style="display: inline-block;width: 34px;height: 40px;background-image: url('/static/img/list.png');background-repeat: no-repeat;background-position: -158px 0px;background-size: 200px;margin: 0 5px;"></a>
        </div>
    </div>

    {% crispy form %}
    <select id="tag" style="width: 60%;" name="interests" multiple="multiple"></select>

    <select id="tag2" style="width: 60%;" name="tools" multiple="multiple"></select>


</div>
<script>
    $(".img-shade").mousemove(function(){
        $(this).find(".shade").show();
    }).mouseout(function(){
        $(this).find(".shade").hide();
    });

    $(".shade").click(function(){
        $("#file").click();
    });

    $(document).ready(function () {

        $("#id-profile-edit-form").append('<input type="file" id="file" name="file" class="none"/>');

        $('#id_interests').val().split(',').forEach(function(data){
            var option = "<option value='"+data+"' selected='selected'>"+data+"</option>";
            $("#tag").append(option);
        });

        $('#id_tools').val().split(',').forEach(function(data){
            var option = "<option value='"+data+"' selected='selected'>"+data+"</option>";
            $("#tag2").append(option);
        });


        $("#tag").replaceAll("#id_interests_edit");

        $("#tag2").replaceAll("#id_tools_edit");

        var tags;

        $.getJSON("/user/auto-complete/interest?p=G",function(result){
            tags = result;
            $("#tag").select2({
                placeholder: "Machine learning techniques you are familiar with. Split with ','",
                tags:tags,
                tokenSeparators: [","]
            });
        });

        $.getJSON("/user/auto-complete/interest?p=G",function(result){
            tags = null;
            tags = result;
            $("#tag2").select2({
                placeholder: "Tools you are familiar with. Split with ','",
                tags:tags,
                tokenSeparators: [","]
            });
        });

    });

    $("#id-profile-edit-form").submit(function() {
        var vals=[], vals2=[];
        $("#tag").select2("data").forEach(function (data) {
            vals.push(data.id);
        });
        vals = vals.join(',');

        $("#tag2").select2("data").forEach(function (data) {
            vals2.push(data.id);
        });
        vals2 = vals2.join(',');

        $('#id_interests').val(vals);
        $('#id_tools').val(vals2);



    });

</script>

{% endblock %}

user/templates/user/forget_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Forget Password{% endblock %}
{% block body %}
{#    <form role="form" action="{% url 'user:forget_password' %}" method="POST">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="submit"/>#}
{#    </form>#}
    <!--{% crispy form %}-->
    <div class="row pt30">
        <div class="col-md-6 col-md-offset-3  col-xs-6 col-xs-offset-3  col-sm-6 col-sm-offset-3">
            <div class="text-center mb20">

                {% if lang.code == 'zh-hans' %}
                    <h3 class="mb10">
                        忘记密码
                    </h3>
                    <p>
                        请输入你的注册邮箱，以便于我们可以发送给你链接让你重置密码
                    </p>
                {% else %}
                    <h3 class="mb10">
                        Forget Password
                    </h3>
                    <p>
                        Please enter your email and we will send you a link by which you can reset your password
                    </p>
                {% endif %}

            </div>
            {% crispy form %}

        </div>
    </div>

<script>
    var checkobj={mail:"email",password:"captcha_1"}

    XformCheck(document.getElementsByClassName("form-horizontal")[0],checkobj);
    $(".form-horizontal").submit(function(){
        var r  = true;
        $("input[checkVal]").each(function(){
            r = r && $(this).attr("checkVal");
        });

        if(r=="false"){
            console.log(r);
            return false;
        }
    });
</script>
{% endblock %}<!DOCTYPE html>

user/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock %}

{% block body %}
    <div class="row pt30">
        <div class="col-md-6 col-md-offset-3  col-xs-6 col-xs-offset-3  col-sm-6 col-sm-offset-3">

            {% if lang.code == 'zh-hans' %}
                <h3>登陆</h3>
                <form id="id-login-form" action="{% url 'user:login' %}" method="post" style="width:300px">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
                <p><a href="{% url 'user:forget_password' %}">忘记密码?</a></p>
            {% else %}
                <h3>Login</h3>
                <form id="id-login-form" action="{% url 'user:login' %}" method="post" style="width:300px">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
                <p><a href="{% url 'user:forget_password' %}">Forgot password?</a></p>
            {% endif %}

        </div>
    </div>

<script>
    var checkobj={password:"password"}

    XformCheck(document.getElementById("id-login-form"),checkobj);
    $("#id-login-form").submit(function(){
        var r  = true;
        $("input[checkVal]").each(function(){
            r = r && $(this).attr("checkVal");
        });
        if(r=="false"){
            return false;
        }
    });

    /*login backgroundimg*/
    /*$('body').css('background','url("../../static/img/blur_bg.jpg") center no-repeat');*/
</script>
{% endblock %}

user/templates/user/pending.html
{% extends 'base.html' %}
{% block title %}Activate your account {% endblock %}
{% block body %}
{#    A validation mail has been sent to {{ user.email }}. Click#}
{#    <a href="{% url 'user:resend_activation_mail' activation.id %}">here</a> to send a new one.#}

    <div class="pt30 text-center">
        
        {% if lang.code == 'zh-hans' %}
            <h1 class="mb10">
                你的账户还未被激活.
            </h1>
            <p>
                请查看你的邮件并按照里面的指示来激活你的账户.
            </p>
            <p>
                重新发了一封邮件.
            </p>
        {% else %}
            <h1 class="mb10">
                Your account hasn't been activated yet.
            </h1>
            <p>
                Please check your email and follow instructions inside to activate your account.
            </p>
            <p>
                We resent an email for your convenience.
            </p>
        {% endif %}


    </div>
{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Register {% endblock %}

{% block body %}
    <div class="row pt30">
        <div class="col-md-5 col-md-offset-3  col-xs-6 col-xs-offset-1  col-sm-6 col-sm-offset-3">

            {% if lang.code == 'zh-hans' %}
                <h3 class="text-center">注册</h3>
                <p class="text-center mb20">每个参赛者只允许有一个账户</p>
            {% else %}
                <h3 class="text-center">Sign Up</h3>
                <p class="text-center mb20">Each individual may have only one account</p>
            {% endif %}
            {% crispy form %}

        </div>
    </div>

<script>
    var checkobj={username:"username",password:"password",display_name:"display_name",real_name:"real_name",mail:"email",password_confirm:"password_confirm",captcha_1:"captcha_1"}

    XformCheck(document.getElementsByClassName("form-horizontal")[0],checkobj);
    $(".form-horizontal").submit(function(){
        var r  = true;
        $("input[checkVal]").each(function(){
            r = r && $(this).attr("checkVal");
        });
        if(r=="false"){
            console.log(r);
            return false;
        }
    });

//    register bgimg
//  $('body').css('background','url("../../static/img/blur_bg.jpg") center no-repeat');
</script>
{% endblock %}

user/templates/user/reset_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Reset Password{% endblock %}
{% block body %}

<div class="row pt30">
    <div class="col-md-6 col-md-offset-3  col-xs-6 col-xs-offset-3  col-sm-6 col-sm-offset-3">

        {% if lang.code == 'zh-hans' %}
            <h3 class="mb10 text-center">重置密码</h3>
        {% else %}
            <h3 class="mb10 text-center">Reset Password</h3>
        {% endif %}

        {% crispy form %}

    </div>
</div>

<script>
    var checkobj={password_confirm:"password_confirm",password:"password"}

    XformCheck(document.getElementsByClassName("form-horizontal")[0],checkobj);
    $(".form-horizontal").submit(function(){

        var r  = true;
        $("input[checkVal]").each(function(){
            r = r && $(this).attr("checkVal");
        });
        if(r=="false"){
            console.log(r);
            return false;
        }
    });
</script>

{% endblock %}